// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `_tokenize_internal_impl`

OnnxInputWrapper tokenize({required String prompt}) =>
    RustLib.instance.api.crateApiTokenizeTokenize(prompt: prompt);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TokenizerWrapper>>
abstract class TokenizerWrapper implements RustOpaqueInterface {
  static TokenizerWrapper fromPretrained({required String modelId}) => RustLib
      .instance
      .api
      .crateApiTokenizeTokenizerWrapperFromPretrained(modelId: modelId);

  OnnxInputWrapper tokenize({required String prompt});
}

class OnnxInputWrapper {
  final Int64List inputIds;
  final Int64List attentionMask;
  final Int64List tokenTypeIds;

  const OnnxInputWrapper({
    required this.inputIds,
    required this.attentionMask,
    required this.tokenTypeIds,
  });

  @override
  int get hashCode =>
      inputIds.hashCode ^ attentionMask.hashCode ^ tokenTypeIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OnnxInputWrapper &&
          runtimeType == other.runtimeType &&
          inputIds == other.inputIds &&
          attentionMask == other.attentionMask &&
          tokenTypeIds == other.tokenTypeIds;
}
